name: Flutter CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build apks
        run: |
          flutter pub get
          flutter build apk --release
          mkdir -p releases
          mv -f build/app/outputs/flutter-apk/*-release.apk releases
          mv -f releases/app-release.apk releases/app-universal-release.apk
      - name: Release to github
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "releases/*-release.apk"
          tag: 1.0