name: Flutter CI

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Set a Tag'
        required: true
        default: ''
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: test output
        run: |
          echo "the current commit ID is $GITHUB_SHA"
          echo "the current tag is ${{ github.event.inputs.TAG }}"